name: themovie
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  http: ^1.2.1
  google_nav_bar: ^5.0.6
  json_annotation: ^4.9.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  youtube_player_flutter: ^9.0.1
  iconsax: ^0.0.8
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
 
    

